-- CSP Report-Only violation sink.
-- Reports are written only by the server-side API using SUPABASE_SERVICE_ROLE_KEY.

BEGIN;

CREATE TABLE IF NOT EXISTS public.csp_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocked_uri TEXT NOT NULL CHECK (char_length(blocked_uri) <= 2048),
    violated_directive TEXT NOT NULL CHECK (char_length(violated_directive) <= 512),
    document_uri TEXT NOT NULL CHECK (char_length(document_uri) <= 2048),
    reported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_csp_violations_reported_at
    ON public.csp_violations (reported_at DESC);

CREATE INDEX IF NOT EXISTS idx_csp_violations_blocked_uri
    ON public.csp_violations (blocked_uri);

ALTER TABLE public.csp_violations ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Post-migration verification:
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_schema = 'public'
--   AND table_name = 'csp_violations'
-- ORDER BY ordinal_position;
--
-- SELECT * FROM public.csp_violations
-- ORDER BY reported_at DESC
-- LIMIT 20;
